export const FETCH_CONTACTS_START = "FETCH_CONTACTS_START";
export const FETCH_CONTACTS_SUCCEEDED = "FETCH_CONTACTS_SUCCEEDED";
export const FETCH_CONTACTS_FAILED = "FETCH_CONTACTS_FAILED";

export const ADD_CONTACT_START = "ADD_CONTACT_START";
export const ADD_CONTACT_SUCCEEDED = "ADD_CONTACT_SUCCEEDED";
export const ADD_CONTACT_FAILED = "ADD_CONTACT_FAILED";

export const REMOVE_CONTACT_START = "REMOVE_CONTACT_START";
export const REMOVE_CONTACT_SUCCEEDED = "REMOVE_CONTACT_SUCCEEDED";
export const REMOVE_CONTACT_FAILED = "REMOVE_CONTACT_FAILED";

export const COMPLETE_CONTACT_START = "COMPLETE_CONTACT_START";
export const COMPLETE_CONTACT_SUCCEEDED = "COMPLETE_CONTACT_SUCCEEDED";
export const COMPLETE_CONTACT_FAILED = "COMPLETE_CONTACT_FAILED";

export default {
	FETCH_CONTACTS_START,
	FETCH_CONTACTS_SUCCEEDED,
	FETCH_CONTACTS_FAILED,
	ADD_CONTACT_START,
	ADD_CONTACT_SUCCEEDED,
	ADD_CONTACT_FAILED,
	EDIT_CONTACT_START,
	EDIT_CONTACT_SUCCEEDED,
	EDIT_CONTACT_FAILED,
	REMOVE_CONTACT_START,
	REMOVE_CONTACT_SUCCEEDED,
	REMOVE_CONTACT_FAILED,
	COMPLETE_CONTACT_START,
	COMPLETE_CONTACT_SUCCEEDED,
	COMPLETE_CONTACT_FAILED,
};